name=WonderUI
version=1.0.0
author=LargeHard Technologies
maintainer=LargeHard Technologies
sentence=A lightweight UI framework for WonderOS on ESP32.
paragraph=WonderUI provides basic graphical elements (buttons, labels, lists) and event handling for small displays, designed specifically for the WonderOS embedded environment.
category=User Interface
url=https://github.com/LargeHardTech/WonderUI
architectures=esp32
depends=U8g2